language: dart
dart: stable
install_dartium: true

before_install:
  - nvm install node
install:
  - (cd functions/ && npm install)

script:
  - cd functions && npm test
  - pub run test --platform vm
  - pub run test --platform dartium
  - dart_analyzer