language: dart
dart: stable
install_dartium: true
dart_task:
  - test: --platform vm
  - test: --platform dartium
  - dartanalyzer: --fatal-warnings lib
  - dartfmt: true
script:
  - ./.functions_build.sh