language: dart

dart:
  - stable

dart_task:
  - test: --platform vm
  - test: --platform dartium
    install_dartium: true
  - dartanalyzer: --fatal-warnings lib
  - dartfmt

cache:
  directories:
    - $HOME/.pub-cache