name: poseidon
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.2.0
  angular2_components: ^0.2.2
  google_maps: ^3.0.0
  firebase: ^3.0.0
  logging: ^0.11.3+1
  js: ^0.6.0
dev_dependencies:
  test: ^0.12.20
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  dart_style: 
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
